name: "fabric-sdk-app-network"

version: 1.0.0

client:
  organization: Org1
  logging:
    level: info
  peer:
    timeout:
      connection: 10s
      response: 180s
      discovery:
        # Expiry period for discovery service greylist filter
        # The channel client will greylist peers that are found to be offline
        # to prevent re-selecting them in subsequent retries.
        # This interval will define how long a peer is greylisted
        greylistExpiry: 10s
  cryptoconfig:
    path: /Users/fuming/Downloads/fabricdev/crypto-config
  credentialStore:
    path: "/tmp/state-store"
    cryptoStore:
      path: /tmp/msp

  BCCSP:
    security:
      enabled: true
      default:
        provider: "SW"
      hashAlgorithm: "SHA2"
      softVerify: true
      level: 256

  tlsCerts:
    systemCertPool: true
    client:
      key:
        path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org1.flxdu.cn/users/User1@org1.flxdu.cn/tls/client.key
      cert:
        path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org1.flxdu.cn/users/User1@org1.flxdu.cn/tls/client.crt

peerPermission: &peerPermission
  endorsingPeer: true
  chaincodeQuery: true
  ledgerQuery: true
  eventSource: true

channelPolicy: &channelPolicy
  #[Optional] options for retrieving discovery info
  discovery:
    #[Optional] discovery info will be retrieved for these number of random targets
    maxTargets: 2
    #[Optional] retry options for retriving discovery info
    retryOpts:
      #[Optional] number of retry attempts
      attempts: 4
      #[Optional] the back off interval for the first retry attempt
      initialBackoff: 500ms
      #[Optional] the maximum back off interval for any retry attempt
      maxBackoff: 5s
      #[Optional] he factor by which the initial back off period is exponentially incremented
      backoffFactor: 2.0
  #[Optional] options for selection service
  selection:
    #[Optional] endorser selection sorting strategy. Possible values: [BlockHeightPriority,Balanced]
    SortingStrategy: BlockHeightPriority
    #[Optional] load-balancer type. Possible values: [RoundRobin,Random]
    Balancer: RoundRobin
    #[Optional] the number of blocks from the highest block number of a group of peers that a peer
    #can lag behind and still be considered to be up-to-date. These peers will be sorted using the
    #given Balancer. If a peer's block height falls behind this threshold then it will be demoted
    #to a lower priority list of peers which will be sorted according to block height.
    #Note: This property only applies to BlockHeightPriority sorter.
    BlockHeightLagThreshold: 5
  #[Optional] options for retrieving channel configuration blocks
  queryChannelConfig:
    #[Optional] min number of success responses (from targets/peers)
    minResponses: 1
    #[Optional] channel config will be retrieved for these number of random targets
    maxTargets: 1
    #[Optional] retry options for query config block
    retryOpts:
      #[Optional] number of retry attempts
      attempts: 5
      #[Optional] the back off interval for the first retry attempt
      initialBackoff: 500ms
      #[Optional] the maximum back off interval for any retry attempt
      maxBackoff: 5s
      #[Optional] he factor by which the initial back off period is exponentially incremented
      backoffFactor: 2.0

  #[Optional] options for the event service
  eventService:
    # [Optional] resolverStrategy specifies the peer resolver strategy to use when connecting to a peer
    # Possible values: [PreferOrg (default), MinBlockHeight, Balanced]
    #
    # PreferOrg:
    #   Determines which peers are suitable based on block height lag threshold, although will prefer the peers in the
    #   current org (as long as their block height is above a configured threshold). If none of the peers from the current org
    #   are suitable then a peer from another org is chosen.
    # MinBlockHeight:
    #   Chooses the best peer according to a block height lag threshold. The maximum block height of all peers is
    #   determined and the peers whose block heights are under the maximum height but above a provided "lag" threshold are load
    #   balanced. The other peers are not considered.
    # Balanced:
    #   Chooses peers using the configured balancer.
    resolverStrategy: PreferOrg

    # [Optional] balancer is the balancer to use when choosing a peer to connect to
    # Possible values: [Random (default), RoundRobin]
    balancer: RoundRobin

    # [Optional] blockHeightLagThreshold sets the block height lag threshold. This value is used for choosing a peer
    # to connect to. If a peer is lagging behind the most up-to-date peer by more than the given number of
    # blocks then it will be excluded from selection.
    # Note that this parameter is applicable only when minBlockHeightResolverMode is set to ResolveByThreshold.
    # Default: 5
    blockHeightLagThreshold: 2

    # [Optional] reconnectBlockHeightLagThreshold - the event client will disconnect from the peer if the peer's
    # block height falls behind the specified number of blocks and will reconnect to a better performing peer.
    # Note that this parameter is only applicable if peerMonitor is set to Enabled (default).
    # Default: 10
    # NOTES:
    #   - Setting this value too low may cause the event client to disconnect/reconnect too frequently, thereby
    #     affecting performance.
    reconnectBlockHeightLagThreshold: 5

    # [Optional] peerMonitorPeriod is the period in which the connected peer is monitored to see if
    # the event client should disconnect from it and reconnect to another peer.
    # Default: 0 (disabled) for Balanced resolverStrategy; 5s for PreferOrg and MinBlockHeight strategy
    peerMonitorPeriod: 3s


grpcOptions: &grpcOptions
  keep-alive-time: 0s
  keep-alive-timeout: 20s
  keep-alive-permit: false
  fail-fast: false
  allow-insecure: true

channels:
  hello1:
    peers:
      peer0.org1.flxdu.cn:
        <<: *peerPermission
        anchorpeer: true
        txpath: /Users/fuming/Downloads/fabricdev/configtx/Org1MSPanchors_hello1.tx
      peer1.org1.flxdu.cn:
        <<: *peerPermission
      peer2.org1.flxdu.cn:
        <<: *peerPermission
      peer3.org1.flxdu.cn:
        <<: *peerPermission
      peer3.org2.flxdu.cn:
        <<: *peerPermission
        anchorpeer: true
        txpath: /Users/fuming/Downloads/fabricdev/configtx/Org2MSPanchors_hello1.tx
      peer3.org3.flxdu.cn:
        <<: *peerPermission
        anchorpeer: true
        txpath: /Users/fuming/Downloads/fabricdev/configtx/Org3MSPanchors_hello1.tx
      peer3.org4.flxdu.cn:
        <<: *peerPermission
        anchorpeer: true
        txpath: /Users/fuming/Downloads/fabricdev/configtx/Org4MSPanchors_hello1.tx
    policies:
      <<: *channelPolicy
    configpath: /Users/fuming/Downloads/fabricdev/configtx/hello1.tx

  hello2:
    peers:
      peer0.org2.flxdu.cn:
        <<: *peerPermission
        anchorpeer: true
        txpath: /Users/fuming/Downloads/fabricdev/configtx/Org2MSPanchors_hello2.tx
      peer1.org2.flxdu.cn:
        <<: *peerPermission
      peer2.org2.flxdu.cn:
        <<: *peerPermission
      peer3.org2.flxdu.cn:
        <<: *peerPermission
    policies:
      <<: *channelPolicy
    configpath: /Users/fuming/Downloads/fabricdev/configtx/hello2.tx

  hello3:
    peers:
      peer0.org3.flxdu.cn:
        <<: *peerPermission
        anchorpeer: true
        txpath: /Users/fuming/Downloads/fabricdev/configtx/Org3MSPanchors_hello3.tx
      peer1.org3.flxdu.cn:
        <<: *peerPermission
      peer2.org3.flxdu.cn:
        <<: *peerPermission
      peer3.org3.flxdu.cn:
        <<: *peerPermission
    policies:
      <<: *channelPolicy
    configpath: /Users/fuming/Downloads/fabricdev/configtx/hello3.tx

  hello4:
    peers:
      peer0.org4.flxdu.cn:
        <<: *peerPermission
        anchorpeer: true
        txpath: /Users/fuming/Downloads/fabricdev/configtx/Org4MSPanchors_hello4.tx
      peer1.org4.flxdu.cn:
        <<: *peerPermission
      peer2.org4.flxdu.cn:
        <<: *peerPermission
      peer3.org4.flxdu.cn:
        <<: *peerPermission
    policies:
      <<: *channelPolicy
    configpath: /Users/fuming/Downloads/fabricdev/configtx/hello4.tx

organizations:
  Org1:
    mspID: Org1MSP
    users:
      User1:
        cert:
          path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org1.flxdu.cn/users/User1@org1.flxdu.cn/msp/cacerts/ca.org1.flxdu.cn-cert.pem
    cryptoPath: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org1.flxdu.cn/users/Admin@org1.flxdu.cn/msp
    peers:
      - peer0.org1.flxdu.cn
      - peer1.org1.flxdu.cn
      - peer2.org1.flxdu.cn
      - peer3.org1.flxdu.cn

  Org2:
    mspID: Org2MSP
    users:
      User1:
        cert:
          path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org2.flxdu.cn/users/User1@org2.flxdu.cn/msp/cacerts/ca.org2.flxdu.cn-cert.pem
    cryptoPath: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org2.flxdu.cn/users/Admin@org2.flxdu.cn/msp
    peers:
      - peer0.org2.flxdu.cn
      - peer1.org2.flxdu.cn
      - peer2.org2.flxdu.cn
      - peer3.org2.flxdu.cn

  Org3:
    mspID: Org3MSP
    users:
      User1:
        cert:
          path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org3.flxdu.cn/users/User1@org3.flxdu.cn/msp/cacerts/ca.org3.flxdu.cn-cert.pem
    cryptoPath: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org3.flxdu.cn/users/Admin@org3.flxdu.cn/msp
    peers:
      - peer0.org3.flxdu.cn
      - peer1.org3.flxdu.cn
      - peer2.org3.flxdu.cn
      - peer3.org3.flxdu.cn

  Org4:
    mspID: Org4MSP
    users:
      User1:
        cert:
          path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org4.flxdu.cn/users/User1@org4.flxdu.cn/msp/cacerts/ca.org4.flxdu.cn-cert.pem
    cryptoPath: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org4.flxdu.cn/users/Admin@org4.flxdu.cn/msp
    peers:
      - peer0.org4.flxdu.cn
      - peer1.org4.flxdu.cn
      - peer2.org4.flxdu.cn
      - peer3.org4.flxdu.cn

  ordererorg:
    mspID: OrdererMSP
    users:
      Admin:
        cert:
          path: /Users/fuming/Downloads/fabricdev/crypto-config/ordererOrganizations/users/Admin@/msp/cacerts/ca.-cert.pem
    cryptoPath: /Users/fuming/Downloads/fabricdev/crypto-config/ordererOrganizations/users/Admin@/msp

orderers:
  orderer.flxdu.cn:
    url: localhost:7050
    grpcOptions:
      ssl-target-name-override: orderer.flxdu.cn
      hostnameOverride: orderer.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/ordererOrganizations/tlsca/tlsca.-cert.pem

peers:
  peer0.org1.flxdu.cn:
    url: localhost:7051
    eventUrl: localhost:7053
    grpcOptions:
      ssl-target-name-override: peer0.org1.flxdu.cn
      hostnameOverride: peer0.org1.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org1.flxdu.cn/tlsca/tlsca.org1.flxdu.cn-cert.pem

  peer1.org1.flxdu.cn:
    url: localhost:7061
    eventUrl: localhost:7063
    grpcOptions:
      ssl-target-name-override: peer1.org1.flxdu.cn
      hostnameOverride: peer1.org1.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org1.flxdu.cn/tlsca/tlsca.org1.flxdu.cn-cert.pem

  peer2.org1.flxdu.cn:
    url: localhost:7071
    eventUrl: localhost:7073
    grpcOptions:
      ssl-target-name-override: peer2.org1.flxdu.cn
      hostnameOverride: peer2.org1.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org1.flxdu.cn/tlsca/tlsca.org1.flxdu.cn-cert.pem

  peer3.org1.flxdu.cn:
    url: localhost:7081
    eventUrl: localhost:7083
    grpcOptions:
      ssl-target-name-override: peer3.org1.flxdu.cn
      hostnameOverride: peer3.org1.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org1.flxdu.cn/tlsca/tlsca.org1.flxdu.cn-cert.pem

  peer0.org2.flxdu.cn:
    url: localhost:7091
    eventUrl: localhost:7093
    grpcOptions:
      ssl-target-name-override: peer0.org2.flxdu.cn
      hostnameOverride: peer0.org2.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org2.flxdu.cn/tlsca/tlsca.org2.flxdu.cn-cert.pem

  peer1.org2.flxdu.cn:
    url: localhost:7101
    eventUrl: localhost:7103
    grpcOptions:
      ssl-target-name-override: peer1.org2.flxdu.cn
      hostnameOverride: peer1.org2.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org2.flxdu.cn/tlsca/tlsca.org2.flxdu.cn-cert.pem

  peer2.org2.flxdu.cn:
    url: localhost:7111
    eventUrl: localhost:7113
    grpcOptions:
      ssl-target-name-override: peer2.org2.flxdu.cn
      hostnameOverride: peer2.org2.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org2.flxdu.cn/tlsca/tlsca.org2.flxdu.cn-cert.pem

  peer3.org2.flxdu.cn:
    url: localhost:7121
    eventUrl: localhost:7123
    grpcOptions:
      ssl-target-name-override: peer3.org2.flxdu.cn
      hostnameOverride: peer3.org2.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org2.flxdu.cn/tlsca/tlsca.org2.flxdu.cn-cert.pem

  peer0.org3.flxdu.cn:
    url: localhost:7131
    eventUrl: localhost:7133
    grpcOptions:
      ssl-target-name-override: peer0.org3.flxdu.cn
      hostnameOverride: peer0.org3.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org3.flxdu.cn/tlsca/tlsca.org3.flxdu.cn-cert.pem

  peer1.org3.flxdu.cn:
    url: localhost:7141
    eventUrl: localhost:7143
    grpcOptions:
      ssl-target-name-override: peer1.org3.flxdu.cn
      hostnameOverride: peer1.org3.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org3.flxdu.cn/tlsca/tlsca.org3.flxdu.cn-cert.pem

  peer2.org3.flxdu.cn:
    url: localhost:7151
    eventUrl: localhost:7153
    grpcOptions:
      ssl-target-name-override: peer2.org3.flxdu.cn
      hostnameOverride: peer2.org3.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org3.flxdu.cn/tlsca/tlsca.org3.flxdu.cn-cert.pem

  peer3.org3.flxdu.cn:
    url: localhost:7161
    eventUrl: localhost:7163
    grpcOptions:
      ssl-target-name-override: peer3.org3.flxdu.cn
      hostnameOverride: peer3.org3.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org3.flxdu.cn/tlsca/tlsca.org3.flxdu.cn-cert.pem

  peer0.org4.flxdu.cn:
    url: localhost:7171
    eventUrl: localhost:7173
    grpcOptions:
      ssl-target-name-override: peer0.org4.flxdu.cn
      hostnameOverride: peer0.org4.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org4.flxdu.cn/tlsca/tlsca.org4.flxdu.cn-cert.pem

  peer1.org4.flxdu.cn:
    url: localhost:7181
    eventUrl: localhost:7183
    grpcOptions:
      ssl-target-name-override: peer1.org4.flxdu.cn
      hostnameOverride: peer1.org4.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org4.flxdu.cn/tlsca/tlsca.org4.flxdu.cn-cert.pem

  peer2.org4.flxdu.cn:
    url: localhost:7191
    eventUrl: localhost:7193
    grpcOptions:
      ssl-target-name-override: peer2.org4.flxdu.cn
      hostnameOverride: peer2.org4.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org4.flxdu.cn/tlsca/tlsca.org4.flxdu.cn-cert.pem

  peer3.org4.flxdu.cn:
    url: localhost:7201
    eventUrl: localhost:7203
    grpcOptions:
      ssl-target-name-override: peer3.org4.flxdu.cn
      hostnameOverride: peer3.org4.flxdu.cn
      <<: *grpcOptions
    tlsCACerts:
      path: /Users/fuming/Downloads/fabricdev/crypto-config/peerOrganizations/org4.flxdu.cn/tlsca/tlsca.org4.flxdu.cn-cert.pem


entityMatchers:
  orderer:
    - pattern: orderer.flxdu.cn:(\d+)
      urlSubstitutionExp: orderer.flxdu.cn:${1}
      sslTargetOverrideUrlSubstitutionExp: orderer.flxdu.cn
      mappedHost: orderer.flxdu.cn

  peer:
    - pattern: (\w+).org1.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org1.flxdu.cn:7051
      sslTargetOverrideUrlSubstitutionExp: ${1}.org1.flxdu.cn
      mappedHost: peer0.org1.flxdu.cn

    - pattern: (\w+).org1.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org1.flxdu.cn:7061
      sslTargetOverrideUrlSubstitutionExp: ${1}.org1.flxdu.cn
      mappedHost: peer1.org1.flxdu.cn

    - pattern: (\w+).org1.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org1.flxdu.cn:7071
      sslTargetOverrideUrlSubstitutionExp: ${1}.org1.flxdu.cn
      mappedHost: peer2.org1.flxdu.cn

    - pattern: (\w+).org1.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org1.flxdu.cn:7081
      sslTargetOverrideUrlSubstitutionExp: ${1}.org1.flxdu.cn
      mappedHost: peer3.org1.flxdu.cn

    - pattern: (\w+).org2.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org2.flxdu.cn:7091
      sslTargetOverrideUrlSubstitutionExp: ${1}.org2.flxdu.cn
      mappedHost: peer0.org2.flxdu.cn

    - pattern: (\w+).org2.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org2.flxdu.cn:7101
      sslTargetOverrideUrlSubstitutionExp: ${1}.org2.flxdu.cn
      mappedHost: peer1.org2.flxdu.cn

    - pattern: (\w+).org2.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org2.flxdu.cn:7111
      sslTargetOverrideUrlSubstitutionExp: ${1}.org2.flxdu.cn
      mappedHost: peer2.org2.flxdu.cn

    - pattern: (\w+).org2.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org2.flxdu.cn:7121
      sslTargetOverrideUrlSubstitutionExp: ${1}.org2.flxdu.cn
      mappedHost: peer3.org2.flxdu.cn

    - pattern: (\w+).org3.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org3.flxdu.cn:7131
      sslTargetOverrideUrlSubstitutionExp: ${1}.org3.flxdu.cn
      mappedHost: peer0.org3.flxdu.cn

    - pattern: (\w+).org3.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org3.flxdu.cn:7141
      sslTargetOverrideUrlSubstitutionExp: ${1}.org3.flxdu.cn
      mappedHost: peer1.org3.flxdu.cn

    - pattern: (\w+).org3.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org3.flxdu.cn:7151
      sslTargetOverrideUrlSubstitutionExp: ${1}.org3.flxdu.cn
      mappedHost: peer2.org3.flxdu.cn

    - pattern: (\w+).org3.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org3.flxdu.cn:7161
      sslTargetOverrideUrlSubstitutionExp: ${1}.org3.flxdu.cn
      mappedHost: peer3.org3.flxdu.cn

    - pattern: (\w+).org4.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org4.flxdu.cn:7171
      sslTargetOverrideUrlSubstitutionExp: ${1}.org4.flxdu.cn
      mappedHost: peer0.org4.flxdu.cn

    - pattern: (\w+).org4.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org4.flxdu.cn:7181
      sslTargetOverrideUrlSubstitutionExp: ${1}.org4.flxdu.cn
      mappedHost: peer1.org4.flxdu.cn

    - pattern: (\w+).org4.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org4.flxdu.cn:7191
      sslTargetOverrideUrlSubstitutionExp: ${1}.org4.flxdu.cn
      mappedHost: peer2.org4.flxdu.cn

    - pattern: (\w+).org4.flxdu.cn:(\d+)
      urlSubstitutionExp: ${1}.org4.flxdu.cn:7201
      sslTargetOverrideUrlSubstitutionExp: ${1}.org4.flxdu.cn
      mappedHost: peer3.org4.flxdu.cn
